### ISSUE TITLE
Cycle Counts

### ISSUE THREAD

**Issue by habemus-papadum** [rekka/avrmultiplication#1]
Hello -- Your blog article was really very helpful and well written -- thank you!  I was wondering how you determined the cycle counts for various versions multiplication at various bit depths -- was this by counting instructions from disassembly of gcc output, or using some other method?

thanks, nehal

**Comment by rekka** [comment]
Dear Nehal, thanks for the message. I'm glad you found it useful. It's been almost 10 years since I worked on this. Yes, you are correct, I just counted the instructions in the gcc output at that time. Unlike modern Intel processors, the instructions on ATMEL RISC chips always take the same number of cycles per instruction. Most take 1 cycle, and the multiplications take 2 if I remember correctly. You can find this info in an ATMEL manual. Hope that helps!
